<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <PackageProjectUrl>https://csharp.sdk.modelcontextprotocol.io</PackageProjectUrl>
    <RepositoryUrl>https://github.com/modelcontextprotocol/csharp-sdk</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <VersionPrefix>2.2.0</VersionPrefix>
    <VersionSuffix></VersionSuffix>
    <Authors>ModelContextProtocol</Authors>
    <Copyright>© Model Context Protocol a Series of LF Projects, LLC.</Copyright>
    <PackageTags>ModelContextProtocol;mcp;ai;llm</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>logo.png</PackageIcon>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <AssemblyOriginatorKeyFile>$(RepoRoot)\Open.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion>2.0.0</PackageValidationBaselineVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common\Polyfills\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(RepoRoot)\logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
